<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0-windows7.0</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWPF>true</UseWPF>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\AUTO_BAZ\AUTO_BAZ.csproj" />
    <ProjectReference Include="..\Prg_Proccessy\Prg_Proccessy.csproj" />
    <ProjectReference Include="..\Prg_UI\Prg_UI.csproj" />
    <Reference Include="Stimulsoft.Base">
      <HintPath>..\Prg_UI\DLLS\stimulydlls\Stimulsoft.Base.dll</HintPath>
    </Reference>
    <Reference Include="Stimulsoft.Report">
      <HintPath>..\Prg_UI\DLLS\stimulydlls\Stimulsoft.Report.dll</HintPath>
    </Reference>
  </ItemGroup>
</Project>
