
namespace Prg_Proccessy.SQLMODELS
{
    public class SIGN
    {
        public int? USERCO { get; set; }
        public bool? FFR_FROOSH { get; set; }
        public bool? FFR_HESAB { get; set; }
        public bool? FFR_MODIR { get; set; }
        public bool? KFR_BAZAR { get; set; }
        public bool? KFR_HESAB { get; set; }
        public bool? KFR_MODIR { get; set; }
        public bool? ANB_RASID_ANB { get; set; }
        public bool? ANB_RASID_QC { get; set; }
        public bool? ANB_HAVL_FROSH { get; set; }
        public bool? ANB_HAVL_ANB { get; set; }
        public bool? ANB_HAVL_MODIR { get; set; }
        public bool? ANB_TOLID_MODIRT { get; set; }
        public bool? ANB_TOLID_QC { get; set; }
        public bool? ANB_TOLID_ANB { get; set; }
        public bool? ANB_KHOROG_ANB { get; set; }
        public bool? ANB_KHOROG_MODIRT { get; set; }
        public bool? ANB_KHOROGS_ANB { get; set; }
        public bool? ANB_KHOROGS_MODIRT { get; set; }
        public bool? SND_TAHI { get; set; }
        public bool? SND_MALI { get; set; }
        public bool? SND_MODIR { get; set; }
        public bool? FFRB_FROOSH { get; set; }
        public bool? FFRB_ANB { get; set; }
        public bool? FFRB_HESAB { get; set; }
        public bool? FFRB_MODIR { get; set; }
        public bool? KFRB_BAZAR { get; set; }
        public bool? KFRB_ANB { get; set; }
        public bool? KFRB_HESAB { get; set; }
        public bool? KFRB_MODIR { get; set; }
        public bool? FFRP_FROOSH { get; set; }
        public bool? FFRP_ANB { get; set; }
        public bool? FFRP_HESAB { get; set; }
        public bool? FFRP_MODIR { get; set; }
        public bool? RASM_HESAB { get; set; }
        public bool? RASM_MODIR { get; set; }
        public bool? PAY_MVAHED { get; set; }
        public bool? PAY_HESAB { get; set; }
        public bool? PAY_MAMEL { get; set; }
        public bool? ENTGH_AZANB { get; set; }
        public bool? ENTGH_BEANB { get; set; }
        public bool? ENTGH_MODIR { get; set; }
        public bool? PAZ_PAZ { get; set; }
        public bool? PAZ_HES { get; set; }
        public bool? PAZ_CEO { get; set; }
        public bool? SGN0124 { get; set; }
        public bool? SGN0224 { get; set; }
        public bool? SGN0324 { get; set; }
        public bool? SGN0126 { get; set; }
        public bool? SGN0226 { get; set; }
        public bool? SGN0326 { get; set; }
        public bool? SGN0133 { get; set; }
        public bool? SGN0233 { get; set; }
        public bool? SGN0333 { get; set; }
        public bool? SGN0132 { get; set; }
        public bool? SGN0232 { get; set; }
        public bool? SGN0332 { get; set; }
        public bool? SGN0134 { get; set; }
        public bool? SGN0234 { get; set; }
        public bool? SGN0334 { get; set; }
        public bool? SGN0135 { get; set; }
        public bool? SGN0235 { get; set; }
        public bool? SGN0335 { get; set; }
        public bool? SGN0136 { get; set; }
        public bool? SGN0236 { get; set; }
        public bool? SGN0336 { get; set; }
        public string? FFR_FROOSHTX { get; set; }
        public string? FFR_HESABTX { get; set; }
        public string? FFR_MODIRTX { get; set; }

        public byte[] KFR_BAZARTX { get; set; }
        public byte[] KFR_HESABTX { get; set; }
        
        public string? KFR_MODIRTX { get; set; }
        public string? ANB_RASID_ANBTX { get; set; }
        public string? ANB_RASID_QCTX { get; set; }
        public string? ANB_HAVL_FROSHTX { get; set; }
        public string? ANB_HAVL_ANBTX { get; set; }
        public string? ANB_HAVL_MODIRTX { get; set; }
        public string? ANB_TOLID_MODIRTTX { get; set; }
        public string? ANB_TOLID_QCTX { get; set; }
        public string? ANB_TOLID_ANBTX { get; set; }
        public string? ANB_KHOROG_ANBTX { get; set; }
        public string? ANB_KHOROG_MODIRTTX { get; set; }
        public string? ANB_KHOROGS_ANBTX { get; set; }
        public string? ANB_KHOROGS_MODIRTTX { get; set; }
        public string? SND_TAHITX { get; set; }
        public string? SND_MALITX { get; set; }
        public string? SND_MODIRTX { get; set; }
        public string? FFRB_FROOSHTX { get; set; }
        public string? FFRB_ANBTX { get; set; }
        public string? FFRB_HESABTX { get; set; }
        public string? FFRB_MODIRTX { get; set; }
        public string? KFRB_BAZARTX { get; set; }
        public string? KFRB_ANBTX { get; set; }
        public string? KFRB_HESABTX { get; set; }
        public string? KFRB_MODIRTX { get; set; }
        public string? FFRP_FROOSHTX { get; set; }
        public string? FFRP_ANBTX { get; set; }
        public string? FFRP_HESABTX { get; set; }
        public string? FFRP_MODIRTX { get; set; }
        public string? RASM_HESABTX { get; set; }
        public string? RASM_MODIRTX { get; set; }
        public string? PAY_MVAHEDTX { get; set; }
        public string? PAY_HESABTX { get; set; }
        public string? PAY_MAMELTX { get; set; }
        public string? ENTGH_AZANBTX { get; set; }
        public string? ENTGH_BEANBTX { get; set; }
        public string? ENTGH_MODIRTX { get; set; }
        public string? PAZ_PAZTX { get; set; }
        public string? PAZ_HESTX { get; set; }
        public string? PAZ_CEOTX { get; set; }
        public string? SGN0124TX { get; set; }
        public string? SGN0224TX { get; set; }
        public string? SGN0324TX { get; set; }
        public string? SGN0126TX { get; set; }
        public string? SGN0226TX { get; set; }
        public string? SGN0326TX { get; set; }
        public string? SGN0133TX { get; set; }
        public string? SGN0233TX { get; set; }
        public string? SGN0333TX { get; set; }
        public string? SGN0132TX { get; set; }
        public string? SGN0232TX { get; set; }
        public string? SGN0332TX { get; set; }
        public string? SGN0134TX { get; set; }
        public string? SGN0234TX { get; set; }
        public string? SGN0334TX { get; set; }
        public string? SGN0135TX { get; set; }
        public string? SGN0235TX { get; set; }
        public string? SGN0335TX { get; set; }
        public string? SGN0136TX { get; set; }
        public string? SGN0236TX { get; set; }
        public string? SGN0336TX { get; set; }
        public bool? SGN0137 { get; set; }
        public bool? SGN0237 { get; set; }
        public bool? SGN0337 { get; set; }
        public string? SGN0137TX { get; set; }
        public string? SGN0237TX { get; set; }
        public string? SGN0337TX { get; set; }
        public bool? SGN0140 { get; set; }
        public bool? SGN0240 { get; set; }
        public bool? SGN0340 { get; set; }
        public string? SGN0140TX { get; set; }
        public string? SGN0240TX { get; set; }
        public string? SGN0340TX { get; set; }
        public bool? SGN0141 { get; set; }
        public bool? SGN0241 { get; set; }
        public bool? SGN0341 { get; set; }
        public string? SGN0141TX { get; set; }
        public string? SGN0241TX { get; set; }
        public string? SGN0341TX { get; set; }
        public bool? SGN0142 { get; set; }
        public bool? SGN0242 { get; set; }
        public bool? SGN0342 { get; set; }
        public string? SGN0142TX { get; set; }
        public string? SGN0242TX { get; set; }
        public string? SGN0342TX { get; set; }
        public DateTime? CRT { get; set; }
        public int? UID { get; set; }
    }
}